// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package input

type GameStartResponse struct {
	Token string `json:"token"`
}

type NftData struct {
	Signature string `json:"signature"`
	Address   string `json:"address"`
	TokenID   string `json:"tokenId"`
	ChainID   int    `json:"chainId"`
}
