// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package input

type CryptogotchiAttributes struct {
	Birthday        int     `json:"birthday"`
	PrimaryColor    string  `json:"primaryColor"`
	BodyColor       string  `json:"bodyColor"`
	FinColor        string  `json:"finColor"`
	PatternQuantity int     `json:"patternQuantity"`
	Species         string  `json:"species"`
	Food            float64 `json:"food"`
}

type GameStartResponse struct {
	Token string `json:"token"`
}

type NftData struct {
	Signature string `json:"signature"`
	Address   string `json:"address"`
	TokenID   string `json:"tokenId"`
	ChainID   int    `json:"chainId"`
}
